#include "../../../shared/entities/entity_reflection.hpp"
#include "placement_tool.hpp"
#include <vector>
#include "../../../shared/editor_grid.hpp"
#include "../../../shared/map.hpp"
#include "../../../shared/shapes.hpp"
#include "../entity_editor_traits.hpp"
#include "../geometry_editor.hpp"
#include "../transaction_system.hpp"

#define ENTITIES_WANT_INCLUDES
#undef ENTITIES_WANT_INCLUDES
#include "imgui.h"
#include "log.hpp"
#include "renderer.hpp"



namespace
{
  linalg::vec3 snap(const linalg::vec3 &v, float step)
  {
    return {editor::snap(v.x, step), editor::snap(v.y, step), editor::snap(v.z, step)};
  }

  
}
namespace client
{


// geometry kinds are at this moment a manually maintained list.
// The entity half comes from placeable_entity_types(), which is generated by the .def.
struct placeable_t
{
  const char *label;
  bool is_geometry;
  shared::geometry_kind_t geometry_kind; // meaningful when is_geometry
  entities::entity_type entity_type;     // meaningful otherwise
};

static const std::vector<placeable_t> &placeables()
{
  static const std::vector<placeable_t> table = [] {
    std::vector<placeable_t> result = {
        {"BOX", true, shared::geometry_kind_t::Box, entities::entity_type::Invalid},
        {"STATIC_MESH", true, shared::geometry_kind_t::Static_Mesh,
         entities::entity_type::Invalid},
        {"DISPLACEMENT", true, shared::geometry_kind_t::Displacement,
         entities::entity_type::Invalid},
    };

    for (entities::entity_type type : entities::placeable_entity_types())
      result.push_back({entities::entity_info(type).display_name, false,
                        shared::geometry_kind_t::Box, type});

    return result;
  }();
  return table;
}

  int Placement_Tool::get_index_of_placeable(const std::string &label)
  {
    const auto &table = placeables();
    for (int idx = 0; idx < (int)table.size(); ++idx)
    {
      if (table[idx].label == label)
        return idx;
    }
    return -1;
  }

void Placement_Tool::on_enable(editor_context_t &ctx)
{
  assert(ctx.map);
  cursor_is_currently_over_surface = false;

  // Default to a box brush — there's a dumb lookup here
  if (!geometry_to_place && !entity_to_place) select_placeable(get_index_of_placeable("BOX"));

}

void Placement_Tool::on_disable(editor_context_t &ctx) { cursor_is_currently_over_surface = false; }

void Placement_Tool::on_update(editor_context_t &ctx,
                               const viewport_state_t &view, float /*dt*/)
{
  float step = ctx.grid ? ctx.grid->step() : editor::MAJOR_GRID_STEP;

  // if we don't hit any level geometry, fall back on the ground plane (y = 0), I believe.
  bool hit_geometry = false;

  if (ctx.bvh && !ctx.bvh->nodes.empty())
  {
    auto hit_result = ray_hit_result_t{};
    if (bvh_intersect_ray(*ctx.bvh, view.mouse_ray.origin, view.mouse_ray.direction,
                          hit_result))
    {
      ghost_position = view.mouse_ray.origin + view.mouse_ray.direction * hit_result.t;
      ghost_position = ::snap(ghost_position, step);
      cursor_is_currently_over_surface = true;
      hit_geometry = true;
    }
  }

  // Fallback: intersect with the Y=0 plane
  if (!hit_geometry)
  {
    linalg::vec3 plane_point = {0, 0.0f, 0};
    linalg::vec3 plane_normal = {0, 1.0f, 0};
    float t = 0.0f;
    if (linalg::intersect_ray_plane(view.mouse_ray.origin, view.mouse_ray.direction,
                                    plane_point, plane_normal, t))
    {
      ghost_position = view.mouse_ray.origin + view.mouse_ray.direction * t;
      ghost_position.x = editor::snap(ghost_position.x, step);
      ghost_position.z = editor::snap(ghost_position.z, step);
      cursor_is_currently_over_surface = true;
    }
    else
    {
      cursor_is_currently_over_surface = false;
    }
  }
}

void Placement_Tool::on_mouse_down(editor_context_t &ctx,
                                   const input::mouse_event_t &e)
{
  if (e.button != input::mouse_button_t::Left || !cursor_is_currently_over_surface)
    return;

  if (geometry_to_place)
  {
    shared::geometry_value_t placed = *geometry_to_place;
    shared::set_position(placed, compute_geometry_placement_center(placed, ghost_position));

    const shared::entity_uid_t uid = ctx.map->add_geometry(placed);

    transaction_builder_t builder;
    builder.add_geometry_created(uid, std::move(placed));
    ctx.transaction_system->push(builder.take());

    *ctx.geometry_updated_so_bvh_rebuild_is_needed = true;
    return;
  }

  if (entity_to_place)
  {

    entities::Entity *clone = entities::clone_entity(entity_to_place.get());
    if (clone == nullptr)
    {
      log_error("got a nullptr entity to place."); return;
    }

    std::shared_ptr<entities::Entity> new_entity(clone, &entities::destroy_entity);

    new_entity->position = compute_placement_center(new_entity.get(), ghost_position);
 
    {
      auto uid = ctx.map->add_entity(new_entity);
      transaction_builder_t builder;
      builder.add_created(uid, snapshot_entity(new_entity.get()));
      ctx.transaction_system->push(builder.take());
    }

    *ctx.geometry_updated_so_bvh_rebuild_is_needed = true;
  }
}

void Placement_Tool::on_mouse_drag(editor_context_t &ctx,
                                   const input::mouse_event_t &e)
{
}

void Placement_Tool::on_mouse_up(editor_context_t &ctx, const input::mouse_event_t &e)
{
}


// A geometry prototype at default size, ready to place.
static shared::geometry_value_t
make_placement_prototype(shared::geometry_kind_t kind)
{
  const linalg::vec3 default_extents{editor::DEFAULT_HALF_EXTENT,
                                     editor::DEFAULT_HALF_EXTENT,
                                     editor::DEFAULT_HALF_EXTENT};

  switch (kind)
  {
    case shared::geometry_kind_t::Box:
    {
      shared::box_geometry_t box;
      box.half_extents = default_extents;
      return box;
    }

    case shared::geometry_kind_t::Static_Mesh:
    {
      shared::static_mesh_geometry_t static_mesh;
      // placeholder mesh.
      static_mesh.surface.mesh_path = "resources/obj/error.obj";
      return static_mesh;
    }

    case shared::geometry_kind_t::Displacement:
    {
      shared::displacement_geometry_t displacement;
      displacement.half_extents = default_extents;
      // Sized but flat: the displacement tool picks the face to sculpt.
      displacement.init_grid(shared::box_face_t::Invalid,
                            displacement.subdivision_level);
      return displacement;
    }
  }

  log_error("make_placement_prototype: unhandled geometry kind {} — using a box",
            (int)kind);
  return shared::box_geometry_t{};
}



void Placement_Tool::select_placeable(int index)
{
  if (index < 0 || index >= (int)placeables().size())
    return;

  selected_type_index = index;
  const placeable_t &placeable = placeables()[index];
  renderer::draw_announcement(placeable.label);

  // Engage exactly one regime.
  geometry_to_place.reset();
  entity_to_place.reset();

  if (placeable.is_geometry)
  {
    geometry_to_place = make_placement_prototype(placeable.geometry_kind);
    return;
  }

  entity_to_place = shared::make_entity(placeable.entity_type);
  if (!entity_to_place)
  {
    log_error("select_placeable: no entity registered for \"{}\"", placeable.label);
    return;
  }

  // Set up defaults for entity types that need them. Trigger_Volume is the only
  // box-volume entity left now that geometry has moved out.
  if (entities::Box_Volume *volume = entities::get_box_volume(entity_to_place.get()))
  {
    volume->half_extents = {editor::DEFAULT_HALF_EXTENT,
                            editor::DEFAULT_HALF_EXTENT,
                            editor::DEFAULT_HALF_EXTENT};
  }
}

void Placement_Tool::on_key_down(editor_context_t &ctx, const key_event_t &e)
{
  for (int idx = 0; idx < (int)placeables().size() && idx < 9; ++idx)
  {
    int key_index = static_cast<int>(input::key_t::Num_1) + idx;
    if (static_cast<int>(e.key) == key_index)
    {
      select_placeable(idx);
      return;
    }
  }
}

void Placement_Tool::on_draw_ui(editor_context_t &ctx)
{
  ImGui::SetNextWindowSize({200, 0}, ImGuiCond_FirstUseEver);
  if (ImGui::Begin("Placement"))
  {
    // Geometry and entities in one list, separated so it's obvious which is
    // which — they behave differently once placed (undo flavor, save form).
    const auto &table = placeables();
    for (int idx = 0; idx < (int)table.size(); ++idx)
    {
      const placeable_t &entry = table[idx];
      if (idx > 0 && table[idx - 1].is_geometry && !entry.is_geometry)
        ImGui::Separator();

      if (ImGui::Selectable(entry.label, idx == selected_type_index))
        select_placeable(idx);
    }
  }
  ImGui::End();
}

void Placement_Tool::on_draw_overlay(editor_context_t &ctx,
                                     overlay_renderer_t &renderer)
{
  if (!cursor_is_currently_over_surface)
    return;

  if (geometry_to_place)
  {
    const linalg::vec3 center =
        compute_geometry_placement_center(*geometry_to_place, ghost_position);
    draw_geometry_ghost(*geometry_to_place, renderer, center);
    return;
  }

  if (entity_to_place)
  {
    linalg::vec3 center =
        compute_placement_center(entity_to_place.get(), ghost_position);

    if (!draw_entity_ghost(entity_to_place.get(), renderer, center))
      draw_default_ghost(entity_to_place.get(), renderer, center);
  }
}

} // namespace client
